name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      continue-on-error: true
      working-directory: /src/ClientesProdutos/
      run: dotnet restore
    - name: Build
      continue-on-error: true
      working-directory: /src/ClientesProdutos/
      run: dotnet build --configuration Release --no-restore
    - name: Test
      continue-on-error: true
      working-directory: /src/ClientesProdutos/
      run: dotnet test --no-restore --verbosity normal
